"""Build the bilingual portfolio from content and case-study data."""
from pathlib import Path
import json, html
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist' if (ROOT / 'dist').is_dir() else ROOT
text = json.loads((OUT / 'content.json').read_text())
projects = json.loads((OUT / 'projects.json').read_text())
def t(key, ko=None, en=None):
    if ko is not None: text[key] = {'ko': ko, 'en': en}
    return f'<span data-i18n="{key}">{text[key]["en"]}</span>'
def photo(src, ko, en, cls='', eager=False):
    return f'<img class="{cls}" src="assets/{src}" alt="{html.escape(en)}" data-alt-en="{html.escape(en)}" data-alt-ko="{html.escape(ko)}" loading="{"eager" if eager else "lazy"}" decoding="async">'
def link(url, label):
    return f'<a class="text-link" href="{url}" target="_blank" rel="noreferrer">{label}</a>'
nav=''.join(f'<a href="#{anchor}">{t(key)}</a>' for anchor,key in [('work','navwork'),('research','navresearch'),('about','navabout'),('contact','navcontact')])
cards=[]
for i,p in enumerate(projects[:5]):
    key=p['id'];img=photo(p['cover'],p['coverAlt']['ko'],p['coverAlt']['en'])
    cards.append(f'''<article class="project-card {key} reveal" id="{key}"><a class="project-open" href="#project/{key}" data-project="{key}">
    <div class="project-image"><div class="image-surface">{img}</div><span class="view-label">{t('viewProject','프로젝트 보기','View project')}</span><span class="project-number">0{i+1}</span></div>
    <div class="project-heading"><h3>{t(key+'Title',p['title']['ko'],p['title']['en'])}</h3><span class="project-year">{p['year']}</span></div>
    <p class="project-summary">{t(key+'Summary',p['summary']['ko'],p['summary']['en'])}</p><p class="project-kind">{t(key+'Kind',p['category']['ko'],p['category']['en'])}</p></a></article>''')
skill=projects[5]
page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Jaewoo Lee — computer vision, wireless digital twins, and software."><meta name="robots" content="index,follow"><link rel="canonical" href="https://jaewoo4200.github.io/"><meta property="og:type" content="website"><meta property="og:title" content="Jaewoo Lee — Research & Software"><meta property="og:description" content="Computer vision, wireless digital twins, 3D tools and apps."><meta property="og:url" content="https://jaewoo4200.github.io/"><meta name="theme-color" content="#fafafa"><title>Jaewoo Lee — Selected work</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='20' fill='%23d8ff36'/%3E%3Ctext x='20' y='28' text-anchor='middle' font-family='Georgia' font-size='28'%3Ej%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"><script defer src="data.js"></script><script defer src="app.js"></script></head><body>
<a class="skip" href="#main">{t('skip')}</a>
<header class="site-header"><a href="#top" class="wordmark" aria-label="Jaewoo Lee home">jaewoo<span class="wordmark-dot">.</span>lee</a><nav aria-label="Primary navigation">{nav}</nav><div class="language-control" role="group" aria-label="Language"><button data-lang="en" aria-pressed="true">EN</button><span>/</span><button data-lang="ko" aria-pressed="false">KO</button></div></header>
<main id="main"><section class="hero" id="top"><div class="hero-top"><p>{t('heroKicker','이재우 · 연구와 소프트웨어','Jaewoo Lee · Research & software')}</p><p>{t('heroLocation','한양대학교 WSL · 학부연구생','Undergraduate researcher · Hanyang WSL')}</p></div>
<h1>{t('heroTitle','공간을 연구하고,<br><em>소프트웨어를 만듭니다.</em>','Computer vision.<br><em>Digital twins & software.</em>')}</h1>
<div class="hero-bottom"><a class="round-link" href="#work">{t('selectedWork','대표 작업','Selected work')}<span class="small-orbit" aria-hidden="true">✳</span></a><p>{t('heroBio','컴퓨터비전으로 공간의 형상과 재질을 연구합니다. 3D 편집 도구와 무선 디지털 트윈, 일상에서 쓰는 작은 앱을 만듭니다.','I study the geometry and materials of physical spaces through computer vision. I build 3D tools, wireless digital twins, and small apps for everyday use.')}</p><span class="hero-year">2025—26</span></div></section>
<section id="work" class="work-section"><div class="section-top reveal"><h2>{t('selectedWork')}</h2><p>{t('workCount','프로젝트 5개 · 도구 1개','Five projects & one toolkit')}</p></div><div class="project-grid">{''.join(cards)}</div>
<a class="toolkit-row reveal" href="#project/reconstruct" data-project="reconstruct"><span class="toolkit-symbol" aria-hidden="true">[ r ]</span><div><p class="eyebrow">{t('toolkitEyebrow','오픈소스 · 에이전트 워크플로','Open source · Agent workflow')}</p><h3>Reconstruct Digital Twin</h3><p>{t('toolkitDesc','원본 자료에서 검토 가능한 3D 장면까지, 출처와 판단 근거를 남기는 에이전트 스킬.','An agent skill for turning scans and photographs into 3D scenes, with a record of the evidence behind each decision.')}</p></div><span class="pill">{t('viewProject')}</span></a></section>
<section class="research-section" id="research"><div class="section-top reveal"><h2>{t('research')}</h2><span>01 {t('publication','논문','publication')}</span></div><article class="paper reveal"><div class="paper-visual">{photo('pipeline.jpg','논문의 시맨틱 재질 식별 파이프라인','Semantic material identification pipeline from the paper')}<span class="paper-stamp">KICS<br>2026</span></div><div class="paper-copy"><p class="eyebrow">{t('firstAuthor')} · June 2026</p><h3>Computer Vision-Assisted Semantic Material Identification for High-Fidelity Digital Twins</h3><p class="authors"><strong>Jaewoo Lee</strong>, Yekaterina Kim, Sunwoo Kim</p><p>{t('paperDesc')}</p><p class="citation">{t('paperCitation','한국통신학회 하계종합학술발표회 논문집, 1942–1943쪽.','KICS Summer Conference Proceedings, pp. 1942–1943.')}</p><div class="paper-links">{link('https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE12964669','DBpia')}{link('assets/kics-2026-paper.pdf',t('paperPDF'))}{link('assets/kics-2026-poster.pdf',t('posterPDF'))}{link('https://github.com/jaewoo4200/SEAM',t('paperSoftware'))}</div><details class="research-detail"><summary>{t('methodResults')}</summary><div class="research-detail-body"><div class="paper-metrics"><p><b>5</b>{t('metricPhotos')}</p><p><b>152</b>{t('metricSegments')}</p><p><b>0.848</b>{t('metricAccuracy')}</p></div><p>{t('paperLimit')}</p></div></details></div></article></section>
<section id="about" class="about-section"><div class="about-copy reveal"><p class="eyebrow">{t('aboutLabel','소개','A little about me')}</p><h2>{t('aboutTitle','이재우입니다.','Hi, I’m Jaewoo.')}<span class="about-flower" aria-hidden="true">✳</span></h2><p>{t('bio')}</p><a class="text-link" href="https://github.com/jaewoo4200" target="_blank" rel="noreferrer">GitHub / jaewoo4200</a></div><div class="experience reveal" id="background"><div class="experience-row"><p>2026 — {t('present')}</p><div><h3>Wireless Systems Laboratory</h3><p>{t('lab')}</p></div></div><div class="experience-row"><p>2023 — 2027</p><div><h3>{t('university')}</h3><p>{t('degree')}</p></div></div><div class="experience-row"><p>2021 — 2022</p><div><h3>{t('previousUniversity')}</h3><p>{t('previousDegree')}</p></div></div><div class="experience-row"><p>2025 — 2026</p><div><h3>HY-HIGH</h3><p>{t('club')}</p></div></div></div></section>
<section id="contact" class="contact-section reveal"><div><p class="eyebrow">{t('contactHeading')}</p><h2>{t('contactTitle','이메일로 연락 주세요.','Get in touch.')}</h2><a class="contact-email" href="mailto:jawlee@hanyang.ac.kr">jawlee@hanyang.ac.kr</a></div><span class="contact-mark" aria-hidden="true">j.</span></section></main>
<footer><p>© 2026 Jaewoo Lee</p><p>{t('footerLabel','컴퓨터비전 · 디지털 트윈 · 소프트웨어','Computer vision · Digital twins · Software')}</p><a href="#top">{t('backTop')}</a></footer>
<dialog class="case-dialog" id="case-dialog" aria-labelledby="case-title"><div class="case-toolbar"><a class="wordmark" href="#work" id="case-home">jaewoo.lee</a><div class="case-toolbar-right"><div class="language-control" role="group" aria-label="Case study language"><button data-lang="en" aria-pressed="true">EN</button><span>/</span><button data-lang="ko" aria-pressed="false">KO</button></div><button class="close-case" id="close-case">{t('close','닫기','Close')} <span aria-hidden="true">×</span></button></div></div><div id="case-content"></div></dialog>
<noscript><style>.reveal{{opacity:1!important;transform:none!important}}</style><p class="noscript-note">Enable JavaScript to read the project case studies and switch languages.</p></noscript>
</body></html>'''
(OUT/'index.html').write_text(page)
(OUT/'content.json').write_text(json.dumps(text,ensure_ascii=False,indent=2)+'\n')
(OUT/'data.js').write_text('const translations = '+json.dumps(text,ensure_ascii=False)+';\nconst projects = '+json.dumps(projects,ensure_ascii=False)+';\n')
print('Built bilingual portfolio and',len(projects),'case studies.')
